### ISSUE TITLE
BUG: If multiple comments open when deleting, you can reply to a non-existent comment and it disappears (no crash)

### ISSUE THREAD

**Issue by jdanish** [theRAPTLab/meme-2023#100]
1. User 1: create comment 1
2. User 2: create reply to comment 1 (reply 1) but leave comment window open
3. User 1 delete comment 1 (it appears as "deleted" as expected)...  leave window open
4. User 2 deletes reply. Their comment and the original now disappear. Comment count is 0.
5. User 1 still sees 2 comments. If they close the comment they disappear. But they can reply to what they see. Then when they save it disappears. No crash / other error I can see.

**Comment by benloh** [comment]
Fixed with 605c5a29132ac19e6c0394e5c68c9f2dea7bfd43

**Comment by benloh** [comment]
But #105 -- if in step 2 User2 doesn't "Save" the reply, User1 deletion will delete the reply being edited.

**Comment by jdanish** [comment]
I think in that super rare case, it is ok if it's slightly confusing.

**Comment by benloh** [comment]
OK.  It was going to be a hairy fix :).

**Comment by jdanish** [comment]
If it becomes an issue, I'd lean towards: If a reply is open, then mark deleted but don't fully remove yet. But I think let's hold off and focus on bigger things that happen more often for now. Thanks!

**Comment by benloh** [comment]
>  If a reply is open, then mark deleted but don't fully remove yet
Yes.  See #105.

One more caveat: It's probably best to discard any project that has this error as the comment ids might be messed up.

**Comment by jdanish** [comment]
OK, when I update the code I'll delete the database and start over.

**Comment by benloh** [comment]
@jdanish should be fixed with `dev-next`. Please confirm and close.
