### ISSUE TITLE
BUG: Process evidence re-attaches if you delete and re-attach evidence

### ISSUE THREAD

**Issue by jdanish** [theRAPTLab/meme-2023#101]
1. Add entities beaver and dam
2. Add process "builds" between beaver and dam (beaver ---- builds ---> dam)
3. Add evidence 1 linked to builds (1a now appears)
4. Delete builds
5. Create a new process, beaver --- likes ---> dam
6. Note, evidence 1a now appears linked to the likes process, but it should have been cleared (we should have to re-link by hand if we want it linked)

Weird, but not super urgent, though it may suggest something else not being cleared?

**Comment by benloh** [comment]
@jdanish should be fixed with `dev-next`. Please confirm and close.
