### ISSUE TITLE
BUG: Deleted evidence links remain on process / entity

### ISSUE THREAD

**Issue by jdanish** [theRAPTLab/meme-2023#102]
1. Create a process
2. Link evidence 1b
3. Delete evidence 1b on the right panel
4. Icon remains on process but should have gone away

NOTE: I tried this in part because editing the target to clear it out also didn't work, though it's OK if it doesn't clear so long as you can effectively delete it.

<img width="919" alt="Screenshot 2024-12-10 at 8 10 30 AM" src="https://github.com/user-attachments/assets/309afd64-fe65-448b-9066-e7d67456f20e">

**Comment by benloh** [comment]
@jdanish should be fixed with `dev-next`. Please confirm and close.
