### ISSUE TITLE
VSCode ESLint error: "prettier/react" has been merged into "prettier" in eslint-config-prettier 8.0.0

### ISSUE THREAD

**Issue by benloh** [theRAPTLab/meme-2023#19]
When starting up VSCode with `meme-2023` `dev` branch, I get the following error after VSCode starts up:

```
Cannot read config file: /Users/loh/dev/meme-2023/node_modules/eslint-config-prettier/react.js Error: "prettier/react" has been merged into "prettier" in eslint-config-prettier 8.0.0. See: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21 Referenced from: /Users/loh/dev/meme-2023/.eslintrc.json
```

![Image](https://github.com/theRAPTLab/meme-2023/assets/1403057/e020c936-8f09-413a-8b8f-df01455d28f2)

**Comment by dsriseah** [comment]
what branch?

**Comment by benloh** [comment]
`dev` branch.  
1. Start VSCode
2. Open `meme-2013` workspace
3. Close VSCode
4. Start VSCode (with MEME workspace previously open)
5. Wait a few seconds until it loads

I'm running the VSCode terminal

**Comment by dsriseah** [comment]
running notes:
I get the error as soon as I load the project:
![Image](https://github.com/theRAPTLab/meme-2023/assets/11952933/6ed1e72e-a593-417f-a0d6-17199e433ba2)

**Comment by dsriseah** [comment]
Looking into the config, I see this:
```eslint
  "parserOptions": {
    "ecmaVersion": 2018,
    "ecmaFeatures": {
      "jsx": true
    },
    "sourceType": "module"
   },
```
I'm up-targeting it to ES2020 which should be fine, but I would have to double-check that all the lint-related plugins are also up to stuff.

Note: the code runs fine; this is the separate **linter** config which runs in VSCode. We don't do a lint pass in webpack, and use the fastest transpiler options (unless those have changed)

**Comment by dsriseah** [comment]
Ran cursory `npm ci; npm run dev`, created admin group for student bob, created model, no errors noted in console.

**Comment by Sakelun** [comment]
> However, fixing this then reveals some **other linting errors** in the codebase. For example, there is a change using an ES2020 feature called **optional chaining** that I had noted earlier, like on line 95 of MEMEStyles
> 
> ```js
>     toolbar: theme?.mixins?.toolbar || '',
> ```
> 
> I'm not sure if this was actually crashing before, or if it was put in as an "upgrade" without testing whether ESLint was correctly targeting ES2020 instead of some earlier version. I'll check that out. Maybe @Sakelun remembers?

I can't say for certain why that was added but it was part of the partially started MUI migration so I think it's safe to assume the lack of a corresponding ESLint configuration update is an oversight.

**Comment by benloh** [comment]
As of 8/14/2024 with the `dev-bl/de-muiify-evidence` branch and 8d571bfdda432513ce4c0cf735f7460c263cb944 this no longer appears to be an issue.
