### ISSUE TITLE
Fix build system linting and npm ci errors

### ISSUE THREAD

**Issue by benloh** [theRAPTLab/meme-2023#21]
After correcting issue #19, new errors in linting were revealed because the new prettier react rules are not equivalent to the older `prettier/react` config. There are also lingering issues with `npm ci` that we'd like to eliminate.

- [ ] rename `.eslintrc.json` to `.estlintrc.js` so we can add comments to it without violating JSON-ness
- [ ] add additional relaxation rules to the config
- [ ] fix the `npm` errors, or at least find out where they are coming from.

**Comment by dsriseah** [comment]
Taking this ticket because it's become a production blocker for Ben with all the new linting errors

**Comment by benloh** [comment]
Fixed with #22 and #23
