### ISSUE TITLE
Badge should match icon from evidence link

### ISSUE THREAD

**Issue by jdanish** [theRAPTLab/meme-2023#35]
The badge icons are still using the old assets, rather than reflecting the new ones in the evidence links. These should be updated.

I think Evan and I are settled on trying this approach which puts the icon in a snug white circle to resolve contrast issue. I've flagged @benloh in Figma to make it easier to find this.

<img width="457" alt="Screenshot 2024-08-15 at 7 42 51 AM" src="https://github.com/user-attachments/assets/3d83d445-0b97-409a-b437-448b38cc1145">

**Comment by benloh** [comment]
Should be working by a4d2df4e564787c09624256f3edf1d873e683a29
