### ISSUE TITLE
How should comment type dropdown default values be handled?

### ISSUE THREAD

**Issue by benloh** [theRAPTLab/meme-2023#42]
>It looks like there is something funny with changing comment types and old values being kept around. I can test more thoroughly and be more specific once you feel ready on that.

_Originally posted by @jdanish in https://github.com/theRAPTLab/meme-2023/issues/41#issuecomment-2377061873_

**Comment by benloh** [comment]
@jdanish A "feature" of the system is that we keep old values around as you switch, just in case change to the wrong type and want to change back again.  Basically the comment data is a big array, where the first item is matched to the first text field, second item to the second field, etc.  This way, if you go from one two-field comment type to a second two-field comment type, your second answer is kept.  And changing types is low cost, meaning you don't have to worry about losing all of your changes if you inadvertently select the wrong type.

I figured it was a low cost way to provide some extra functionality if you change types.

But if you prefer that we clear out any existing text when you select a new type, then we need to be more sophisticated about handing that.

Or are you seeing some other weird functionality?

**Comment by jdanish** [comment]
I think what I am seeing is that when there is now a drop-down selection, I assumed it was "set" if I left the default and that didn't appear. If I then change it away and back it works. So maybe it was just the dropdown but that's what was funny.

**Comment by jdanish** [comment]
Sure:

1: Create new comment where the first field is a dropdown

<img width="361" alt="Screenshot 2024-09-26 at 4 08 16 PM" src="https://github.com/user-attachments/assets/e35d9dde-b1ed-4f49-a65e-f036fa603a37">

2: Leave it on the default value and press save.

<img width="359" alt="Screenshot 2024-09-26 at 4 08 22 PM" src="https://github.com/user-attachments/assets/e8d985b5-e706-4b56-b39b-d67c8ee03669">

It thinks nothing was selected. Select something else and then change it back to default. Press save and it now reports correctly.

**Comment by benloh** [comment]
Ah!  That is a different problem.  

@jdanish So this is a question for how you would like to handle dropdowns.  When you first open a comment with a dropdown do you:

a) default to selecting the first item in the menu? or

b) show a blank item or something like "select an option" and force the user to make an explicit selection?

I can see an argument for either one.  It kind of depends on how you want to handle the interaction.  I'm inclined to go with b) so that we're forcing the user to make an explicit decision, plus it forces you to review the available options.  But it does slow things down.

I'm a little surprised we didn't encounter this already with Net.Create, but it might be because we're handling data differently.  Will have to go back and review...See [#282](https://github.com/netcreateorg/netcreate-itest/issues/282)

**Comment by jdanish** [comment]
I think we did with the node type and edge type where we always include a blank as the first option to address / avoid this. I think that'd be fine. Which is easier?  More flexible would be - set to the first as default, and then the author can decide to default to an option or a blank. For consistency I think we'd want that. But the alternative is to insert a blank always. I'm leaning toward the first one (so we just put a blank if we want it, and either way you handle it).

**Comment by benloh** [comment]
Defaulting to selecting the first is a little harder to implement, but from a user admin perspective makes a lot more sense.  So let's go with that.  So if you wanted a blank, you would do do something like this:

```
    options: ['', '🥲 No', '🤔 A little', '😀 A lot'],
```
But we'd have to make sure we catch all the possibilities (e.g. empty string ("") and space (" ") and blank/select ("blank" || "select one").

**Comment by benloh** [comment]
@jdanish The first item in a dropdown should now be automatically selected.  Please verify that this addresses the "something funny with changing comment types" problem.

**Comment by jdanish** [comment]
Verified - looks good
