### ISSUE TITLE
Handling comment thread deletion for admins

### ISSUE THREAD

**Issue by benloh** [theRAPTLab/meme-2023#56]
In NC's comment system, deleting comment threads is somewhat complicated, depending on whether or not you're an admin.

https://github.com/netcreateorg/netcreate-itest/issues/139

For normal users:
* comments at the end of a thread are simply deleted
* comments deleted from the middle of a thread are marked [DELETED] with a placeholder

For admins only: 
* comments deleted from the middle of a thread are pruned -- all subsequent comments in the thread are deleted, but other thread roots are left alone
* only admins are allowed to delete a thread root

Since there is no notion of an admin user working on a project, should teachers be considered admin users with the power to delete threads?

This is potentially further complicated by different users:
* should comments behave differently when viewed by a teacher
* should comments behave different when viewed by someone not in your group?
* should a fellow group member be allowed to delete your comment?

@jdanish any thoughts?

**Comment by jdanish** [comment]
> Since there is no notion of an admin user working on a project, should teachers be considered admin users with the power to delete threads?

Yes!

For the others, let's keep it simple and make it that everyone sees the same comments in the same ways and you can only delete what you created, or the teacher has to as specified. I'd rather not over-complicate this unless we see a need when students use it.

**Comment by benloh** [comment]
Implemented a822d417bc4d777c2f052c1c4d3cef3ac7aaaee1
