### ISSUE TITLE
deleting a comment generates a popup that you have a new comment

### ISSUE THREAD

**Issue by benloh** [theRAPTLab/meme-2023#68]
Joshua writes: 
deleting a comment generates a popup that you have a new comment, but I think that'd be one case we want to ignore if it is easy?

**Comment by benloh** [comment]
@jdanish Currently as of 10/10/2024 on http://rapt.inquirium.org:3000/#/ deleting a comment does not seem to generate a new status update.

**Comment by jdanish** [comment]
Now I cannot reproduce it either. Closing and will re-open if I figure it out. Sorry!

**Comment by benloh** [comment]
I'm also having trouble reproducing the Evidence Link comment appearing in the wrong place, but I'm pretty sure I saw it earlier too.  There may have been an error condition in there somewhere, or it's also possible there's an async issue.
