### ISSUE TITLE
FEATURE: Please increase the contrast on the liker scale comments

### ISSUE THREAD

**Issue by jdanish** [theRAPTLab/meme-2023#70]
Students report that they can barely distinguish between 4 and 5 stars, and request we increase the contrast in selected v/ not-selected. Not super urgent, but if they are struggling to see it then no doubt some kids will. 

![Screenshot 2024-10-10 at 4 19 37 PM](https://github.com/user-attachments/assets/8b67aaf7-4a00-401a-843a-17d02856020f)
![Screenshot 2024-10-10 at 4 19 53 PM](https://github.com/user-attachments/assets/e1f934b5-fac8-41dd-a023-23ce044a5988)

**Comment by benloh** [comment]
Not selected is now much lighter.
Hover (star #5) is now more visible.

![Image](https://github.com/user-attachments/assets/de250b84-0059-4ad1-8060-eb0d5ed34b8c)

**Comment by benloh** [comment]
Also, when disabled (not being edited), buttons are now darker:

![Image](https://github.com/user-attachments/assets/9db43caa-e29b-4541-9992-f30c8397f25e)

**Comment by benloh** [comment]
@jdanish please let me know if the fix is good enough.  (Should be on the `urcomment` branch).

**Comment by jdanish** [comment]
Yes thanks!
