### ISSUE TITLE
"Add Process" button to connect VMechs

### ISSUE THREAD

**Issue by benloh** [theRAPTLab/meme-2023#82]
Easier connecting of entities (Drag and drop? Or “add process” when selected?)
Technically a "nice to have" but high marked "must have" for completion.

**Comment by benloh** [comment]
Implemented with 6cebedd48763b2865854f016640a8145528986e2

@jdanish Is this what you had in mind?
1. `git checkout dev-bl/ui-refine`
2. Open a model
3. Create a new Entity
4. Select the entity => "Add process" button shows in bottom control bar
5. Create a new Outcome
6. Select the outcome  => "Add process" button shows in bottom control bar

**Comment by jdanish** [comment]
Yes thanks! I think it just makes it a bit simpler for kids.
